# Generated by Django 5.0.2 on 2024-02-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='definition',
            new_name='description',
        ),
    ]
