# Generated by Django 5.0.2 on 2024-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_definition_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
