# Generated by Django 5.0.2 on 2024-02-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_orderitem_date_remove_orderitem_total_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="description",
        ),
    ]
