# Generated by Django 5.0.2 on 2024-02-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_orderitem_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='block',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
