# Generated by Django 5.0.2 on 2024-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.DateField(),
        ),
    ]
