# Generated by Django 5.0.2 on 2024-02-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="date",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="user",
        ),
    ]
