# Generated by Django 5.0.2 on 2024-02-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='block',
            field=models.CharField(choices=[('Dona', 'Dona'), ('Blok', 'Blok')], max_length=250, null=True),
        ),
    ]
